# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-demo
  namespace: argo-demo
  labels:
    app: argo-demo
spec:
  selector:
    matchLabels:
      app: argo-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: argo-demo
    spec:
      containers:
        - name: argo-demo
          image: nginx:1.23.0
          ports:
            - containerPort: 80
              name: argo-demo
